Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "lab01-centos-maq-04"
  config.vm.network "private_network", ip: "192.168.56.5", hostname: true
  config.vm.provision "shell", path: "maq-04.sh"
  #config.vm.network "forwarded_port", guest: 8080, host:8080
end 