Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"
  config.vm.hostname = "lab01-debian-maq-03"
  config.vagrant.plugins = "vagrant-vbguest"
  config.vbguest.auto_update = false
  config.vm.network "private_network", ip: "192.168.56.4", hostname: true
  config.vm.provision "shell", path: "maq-03.sh"
  # config.vm.network "forwarded_port", guest: 8080, host:8080
end