Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"
  config.vm.hostname = "lab01.debian.maq.03"
  config.vm.network "lab_network", ip: "192.168.56.4", hostname: true
  # config.vm.network "forwarded_port", guest: 8080, host:8080
end